## Python: some useful things to know

You are strongly encouraged to learn Python on your own if you are not familiar with the language -- we have only limited time to spend on the language basics. 

We use Python >= 3.9, some of the features might not be available in prior versions (definitely not python 2)

There is a number of materials to learn Python online, for example:

- https://www.programiz.com/python-programming/tutorial -- a short tutorial
- https://docs.python.org/3/tutorial/index.html#tutorial-index -- official tutorial
- https://docs.python.org/3/library/index.html#library-index -- more extensive library documentation.

Following ere are some useful constructs that you will use a lot in the course.



Try to predict what is the output of each command before you run it!

### Lists

In [ ]:
my_list = [0, 1, 2, 3, 4, 5]
print(my_list[0])   # Index from the start of array

0


In [ ]:
print(my_list[-1])  # Index from the end of array

5


In [ ]:
print(my_list[3:])   # Slice

In [ ]:
print(my_list[:3])   # Slice

In [ ]:
print(my_list[::2])  # Slice

In [ ]:
my_list.append(6)
print(my_list)

[0, 1, 2, 3, 4, 5, 6]


In [ ]:
another_list = [7, 8, 9]
concat = my_list + another_list
print(concat)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
print(concat.pop())
print(concat)


In [ ]:
print(len(concat))

In [ ]:
print(min(concat))
print(max(concat))

In [ ]:
print(2 in concat)
print(10 in concat)

True
False


In [ ]:
a = 10
b = a
b = 20
print(a)
print(b)

10
20


In [ ]:
xs = [1, 2, 3]
ys = xs
ys[0] = 5
print(xs)
print(ys)



[5, 2, 3]
[5, 2, 3]


In [ ]:
def append_new(my_list=[]):
    my_list.append(1)
    return my_list


print(append_new())
print(append_new())


[1]
[1, 1]


### Tuples

In [ ]:
xs = ("a", 1, True) 

print(xs[2])

True


In [ ]:
x,y,z = xs
print(y)

1


In [ ]:
a, b = 1, 2
a, b = b, a
print(a, b)

2 1


### Dictionaries

In [ ]:
my_dict = dict(a=0, b=1, e=2)
# OR
# my_dict = {"a":0, "b":1, "c":2}
print(my_dict["a"])
my_dict["d"] = 3

0


In [ ]:
another_dict = dict(e=4)
my_dict.update(another_dict)
print(my_dict)

{'a': 0, 'b': 1, 'e': 4, 'd': 3}


In [ ]:
print("e" in my_dict)
print("f" in my_dict)
print(0 in my_dict)

True
False
False


### Sets

In [ ]:
my_set = set([1, 2, 3])
# OR
# my_set = {1, 2, 3}
print(len(my_set))

3


In [ ]:
print({1,2,3}.union({3,4,5}))

{1, 2, 3, 4, 5}


In [ ]:
print({1,2,3}.intersection({3,4,5}))

{3}


### Loops

Easy way to construct arrays/sets/dictionaries based on filtering etc.

In [ ]:
for x in range(5):
    print(x)

In [ ]:
for x in ["a", "b", "c"]:
    print(x)

In [ ]:
for i, x in enumerate(["a","b","c"]):
    print(i, x)

0 a
1 b
2 c


In [ ]:
my_dict = dict(a=0, b=1, c=2)
# OR my_dict = {"a":0, "b":1, "c":2}
for v in my_dict:
    print(v)

a
b
c


In [ ]:
for k, v in my_dict.items():
    print(k, v)

a 0
b 1
c 2


In [ ]:
list_of_tuples = [("a", 1, True), ("b", 2, False), ("c", 3, True)]
for a, b, c in list_of_tuples:
    print(a, b ** 2, not c)

a 1 False
b 4 True
c 9 False


In [ ]:
my_list = [x ** 2 for x in range(5)]
print(my_list)

In [ ]:
my_set = {x for x in range(5) if x > 2}
print(my_set)

In [ ]:
for i, j in zip(["a", "b", "c"], [1, 2, 3]):
    print(i, j)

a 1
b 2
c 3


In [ ]:
zipped = [("a",1), ("b",2), ("c",3)]
print(*zipped)
unzipped = list(zip(*zipped))
print(unzipped)

('a', 1) ('b', 2) ('c', 3)
[('a', 'b', 'c'), (1, 2, 3)]


In [ ]:
for x in "ař日й":  # A string is a list of utf-8 chars
    print(x)

a
ř
日
й


### Generators, itertools

**Generator** functions allow you to declare a function that behaves like an iterator, i.e. it can be used in a for loop. However they do not need to allocate all of the memory upfront -- they can be used in a similar way as lazy evaluation in Haskell.

In [ ]:
def my_range(n):
    i = 0
    while i < n:
        yield i
        i += 1


print(my_range(5))


<generator object my_range at 0x7f822a68cf50>


In [ ]:
for i in my_range(5):
    print(i)

0
1
2
3
4


In [ ]:
print(list(my_range(5)))

**Itertools** implement a number of iterator building blocks inspired by constructs from APL, Haskell, and SML. Each has been recast in a form suitable for Python.

https://docs.python.org/3/library/itertools.html

In [ ]:
import itertools

In [ ]:
for i in itertools.chain(my_range(5), my_range(5)):
    print(i)

0
1
2
3
4
0
1
2
3
4


In [ ]:
vocabulary = ["animal", "boy", "beard", "arm", "clock", "ceiling", "clean", "bribe"]
vocabulary = sorted(vocabulary)

for key, group in itertools.groupby(vocabulary, lambda x: x[0]):
    key_and_group = {key: list(group)}
    print(key_and_group)

{'a': ['animal', 'arm']}
{'b': ['beard', 'boy', 'bribe']}
{'c': ['ceiling', 'clean', 'clock']}


In [ ]:
for x in itertools.combinations("ABCD", 2):
    print(x)

('A', 'B')
('A', 'C')
('A', 'D')
('B', 'C')
('B', 'D')
('C', 'D')


In [ ]:
for x in itertools.product("ABC", "XYZ"):
    print(x)

In [ ]:
for p in itertools.permutations("123"):
    print(p)

('1', '2', '3')
('1', '3', '2')
('2', '1', '3')
('2', '3', '1')
('3', '1', '2')
('3', '2', '1')


See more examples at https://docs.python.org/3/library/itertools.html

Some other collections might be useful: https://docs.python.org/3/library/collections.html

- OrderedDict: a dict subclass that remembers the order entries were added
- namedtuple(): a factory function for creating tuple subclasses with named fields
- defaultdict: a dict subclass that calls a factory function to supply missing values
- Counter: a dict subclass for counting hashable objects
- deque: a list-like container with fast appends and pops on either end

### Numpy

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

Numpy resources (very much recommended to learn the API!):

- cheatsheet: https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf
- documentation https://numpy.org/doc/1.22/user/whatisnumpy.html

In [ ]:
import numpy as np

x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(x)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(x.T)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
print(x[1, :])

[4 5 6]


In [ ]:
print(x[:, 2])

[3 6]


In [ ]:
print(x[1:, 1:2])

[[5]]


In [ ]:
print(x * 2)  # Broadcast!

[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
y = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

In [ ]:
print(x @ y)  # Matrix multiplication

[[22 28]
 [49 64]]


In [ ]:
print(x * y.T)   # Element-wise multiplication

[[ 1  6 15]
 [ 8 20 36]]


In [ ]:
x = np.zeros((2,))  # Vector.
print(x, x.shape)


[0. 0.] (2,)


In [ ]:
x = np.zeros((2,3))  # Matrix
print(x, x.shape)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)


In [ ]:
x = np.zeros((2,3,3))  # Tensor
print(x, x.shape)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]] (2, 3, 3)


### Typing

We use type annotations (Python>=3.5) extensively in these labs. They serve mostly as a comment - they are not strictly enforced by the Python interpreter, unlike what compilers of strongly typed languages such as C/C++ enforce.

- https://docs.python.org/3/library/typing.html

Basic types:
- int
- float
- str

Needs to be imported from `typing` package:

- List[item_type]
- Set[item_type]
- Tuple[type_list]
- Dict[key_type, value_type]
- Iterable[item_type]
- Union[type_list]
- Callable[[input_types], output_type]

Note that in newer versions of Python you can directly use lowercase list/dict/tuple/set types without special imports

In [ ]:
from typing import List

def concat(xs: List[str]) -> str:
    return "".join(xs)


concat(["a", "b", "c"])

'abc'

### Special (magic) methods

In [ ]:
class MyConfig:
    def __init__(self, 
                 my_required_config: str, 
                 defaulted_value: int = 10, 
                 **kwargs: dict):
        """
        This is a constructor.

        **kwargs are all remaining unlisted keyword arguments.
        """
        self.my_required_config = my_required_config
        self.defaulted_value = defaulted_value
        self.other_config = kwargs

    def __str__(self):
        """
        This function is called on str(obj)
        """
        return self.my_required_config

    def __hash__(self):
        """
        This function is called when we need to hash the object
        (in dictionaries or sets)
        """
        return hash(self.my_required_config)

    def __repr__(self):
        """
        Magic function that is called for a human-friendly representation,
        called in jupyter notebooks on the last object in the cell.
        """
        listed_items = "\n".join(
            f"{key}={value}" for key, value in self.other_config.items()
        )
        return f"{self.my_required_config} {self.defaulted_value}\n###\n{listed_items}"


obj = MyConfig("example", epsilon=1e-6, gamma=1e-2)
obj

In [ ]:
hash(obj)

-2128925855013212990

### Things to be careful about

And more... It is useful to know about some Python "gotchas", so you are not so surprised by unexpected behavior.

- https://www.geeksforgeeks.org/gotcha)s-in-python/
- https://towardsdatascience.com/five-python-gotchas-3073145fe083
- https://sopython.com/wiki/Common_Gotchas_In_Python
- https://8thlight.com/blog/shibani-mookerjee/2019/05/07/some-common-gotchas-in-python.html
- https://stackoverflow.com/questions/1011431/common-pitfalls-in-python